CREATE DATABASE PERSONAL;
USE PERSONAL;
CREATE TABLE DATA(ID INT, NAME VARCHAR(20), AGE INT,OCCUPATION VARCHAR(20),INCOME INT);
INSERT INTO DATA VALUES(1,'ACHU',34,'ACTOR',80000000),(2,'AKHINASH',27,'ENGINEER',3500000),
(3,'RAMBO',22,'STUDENT',20000);
SELECT*FROM DATA;
SELECT*FROM DATA departments
WHERE AGE>30;
SELECT*FROM DATA
ORDER BY INCOME DESC; 
SELECT DISTINCT OCCUPATION FROM DATA;
SELECT * FROM DATA 
WHERE INCOME BETWEEN 35000 AND 9000000;

CREATE TABLE DATAS AS SELECT *FROM DATA;
SELECT*FROM DATAS;
DROP TABLE DATAS;


CREATE TABLE Departments (
    DepartmentID INT PRIMARY KEY,
    DepartmentName VARCHAR(100)
);

CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    StudentName VARCHAR(100),
    Age INT,
    DepartmentID INT,
    FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
);

INSERT INTO Departments (DepartmentID, DepartmentName) VALUES 
(1, 'Computer Science'),
(2, 'Mechanical Engineering'),
(3, 'Electrical Engineering');

INSERT INTO Students (StudentID, StudentName, Age, DepartmentID) VALUES 
(1, 'Alice', 20, 1),
(2, 'Bob', 22, 2),
(3, 'Charlie', 21, 3);

UPDATE DEPARTMENTS
SET DEPARTMENTNAME ='MECHOO'
WHERE DEPARTMENTID=2;

ALTER TABLE STUDENTS ADD COLUMN EMAIL VARCHAR(50);
DELETE FROM STUDENTS WHERE STUDENTID=2;
TRUNCATE TABLE DEPARTMENTS;
DROP TABLE STUDENTS;
show databases;
-- SQL FUNCTIONS
-- STRING FUNCT