use tech;
CREATE TABLE COUNTRY(
CCODE VARCHAR(10) PRIMARY KEY,
CNAME VARCHAR(20));

INSERT INTO COUNTRY VALUES
('BN','BANGLADESH'),
('IN','INDIA'),
('NP','NEPAL'),
('PK','PAKISTAN'),
('SL','SRILANKA');

SELECT * FROM COUNTRY;

CREATE TABLE CAPITAL(
CAPID VARCHAR(10) PRIMARY KEY,
CCODE VARCHAR(10) ,
CAPNAME VARCHAR(20),
FOREIGN KEY(CCODE) REFERENCES COUNTRY(CCODE));

INSERT INTO CAPITAL VALUES
('C1','IN','NEW DELHI'),
('C2','PK','ISLAMABAD'),
('C3','NP','KATHMANDU');

SELECT * FROM CAPITAL;

SELECT * FROM COUNTRY INNER JOIN CAPITAL ON COUNTRY.CCODE=CAPITAL.CCODE;
SELECT * FROM COUNTRY LEFT JOIN CAPITAL ON COUNTRY.CCODE=CAPITAL.CCODE;
SELECT * FROM COUNTRY RIGHT JOIN CAPITAL ON COUNTRY.CCODE=CAPITAL.CAPNAME;

SELECT * FROM COUNTRY LEFT JOIN CAPITAL ON COUNTRY.CCODE=CAPITAL.CAPNAME
UNION
SELECT * FROM COUNTRY RIGHT JOIN CAPITAL ON COUNTRY.CCODE=CAPITAL.CAPNAME;





CREATE TABLE employees1 (
    ID INT PRIMARY KEY,
    Name VARCHAR(50)
);

INSERT INTO employees1 (ID, Name) VALUES
(1, 'John'),
(2, 'Jane'),
(3, 'Joe');

CREATE TABLE employees2 (
    ID INT PRIMARY KEY,
    Name VARCHAR(50)
);

INSERT INTO employees2 (ID, Name) VALUES
(2, 'Jane'),
(3, 'Joe'),
(4, 'Sarah');

SELECT*FROM EMPLOYEES1;
SELECT*FROM EMPLOYEES2;

SELECT*FROM EMPLOYEES1
UNION
SELECT*FROM EMPLOYEES2;

SELECT*FROM EMPLOYEES1
UNION ALL
SELECT*FROM EMPLOYEES2;








